title: notes.lochana
description: getting smarter everyday
theme: just-the-docs

url: https://fivetwentythree.github.io/test-doc

aux_links:
  Template Repository: https://github.com/fivetwentythree/test-doc
